name: CI

on: [ push, pull_request ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Restore tools
        run: dotnet tool restore

      - name: Check code format
        run: dotnet fantomas --check .


  ci-linux:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test with local source files and no embedded sources
        run: dotnet test -c Release -p:DeterministicSourcePaths=false -p:EmbedAllSources=false

      - name: Clean
        run: dotnet clean -c Release

      - name: Test with deterministic source paths and embedded sources
        run: dotnet test -c Release -p:DeterministicSourcePaths=true -p:EmbedAllSources=true


  ci-win:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test with local source files and no embedded sources
        run: dotnet test -c Release -p:DeterministicSourcePaths=false -p:EmbedAllSources=false

      - name: Clean
        run: dotnet clean -c Release

      - name: Test with deterministic source paths and embedded sources
        run: dotnet test -c Release -p:DeterministicSourcePaths=true -p:EmbedAllSources=true


  ci-mac:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test with local source files and no embedded sources
        run: dotnet test -c Release -p:DeterministicSourcePaths=false -p:EmbedAllSources=false

      - name: Clean
        run: dotnet clean -c Release

      - name: Test with deterministic source paths and embedded sources
        run: dotnet test -c Release -p:DeterministicSourcePaths=true -p:EmbedAllSources=true


  publish:

    runs-on: ubuntu-latest

    needs:
      - lint
      - ci-linux
      - ci-win
      - ci-mac

    steps:
      - uses: actions/checkout@v3

      - name: Pack
        run: dotnet pack -c Release src/Faqt/Faqt.fsproj

      - name: Push
        if: startsWith(github.ref, 'refs/tags/v/')
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "**/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k "$NUGET_API_KEY" --skip-duplicate
